name: CI

on:
  pull_request:
    branches:
      - main
    paths:
        - "impl/csharp/**"
        - ".github/workflows/pr-cs-test.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run unit tests
      run: dotnet test --configuration Release --no-restore --verbosity normal
